"""
Khadee EDA — HTML Renderer
============================
Builds the complete HTML report with embedded CSS, JS, and Plotly CDN.
"""

import os

from ..config import SECTION_LABELS


def render_html(title, sections_html, sections_list):
    """
    Build the complete HTML report.

    Parameters
    ----------
    title : str
        Report title.
    sections_html : dict
        {section_id: html_content} for each generated section.
    sections_list : list
        Ordered list of section IDs to include.

    Returns
    -------
    str : Complete HTML document.
    """
    css = _load_asset("style.css")
    js = _load_asset("script.js")

    # Build sidebar navigation
    nav_html = _build_nav(sections_list)

    # Build sections
    body_html = ""
    for section_id in sections_list:
        if section_id in sections_html:
            body_html += f'<section class="report-section" data-section="{section_id}">'
            body_html += sections_html[section_id]
            body_html += '</section>'

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Khadee EDA — Deep Insights Data Profiling Report">
    <title>{title} — Khadee EDA</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap" rel="stylesheet">
    <script src="https://cdn.plot.ly/plotly-2.27.0.min.js"></script>
    <style>
{css}
    </style>
</head>
<body>
    <!-- Sidebar Navigation -->
    <nav class="sidebar" id="sidebar">
        <div class="sidebar-header">
            <div class="logo">
                <span class="logo-text">Khadee EDA</span>
            </div>
            <div class="report-title-sm">{title}</div>
        </div>
        <div class="nav-links">
            {nav_html}
        </div>
        <div class="sidebar-footer">
            <div class="powered-by">Powered by Khadee EDA v1.0.0</div>
        </div>
    </nav>

    <!-- Main Content -->
    <main class="main-content" id="main-content">
        <header class="report-header">
            <h1 class="report-title">{title}</h1>
            <p class="report-subtitle">Deep Insights Data Profiling Report — Powered by Khadee EDA</p>
        </header>

        <div class="sections-container">
            {body_html}
        </div>

        <footer class="report-footer">
            <p>Generated by <strong>Khadee EDA</strong> — Deep Insights Data Profiling</p>
        </footer>
    </main>

    <!-- Mobile menu toggle -->
    <button class="mobile-menu-btn" id="mobile-menu-btn" onclick="toggleSidebar()">☰</button>

    <script>
{js}
    </script>
</body>
</html>"""

    return html


def _build_nav(sections_list):
    """Build sidebar navigation links."""
    nav = ""
    for section_id in sections_list:
        label = SECTION_LABELS.get(section_id, section_id.replace("_", " ").title())
        nav += f'<a class="nav-link" href="#section-{section_id}" data-section="{section_id}">{label}</a>\n'
    return nav


def _load_asset(filename):
    """Load a CSS or JS asset file."""
    assets_dir = os.path.join(os.path.dirname(os.path.dirname(__file__)), "assets")
    filepath = os.path.join(assets_dir, filename)
    try:
        with open(filepath, "r", encoding="utf-8") as f:
            return f.read()
    except FileNotFoundError:
        return f"/* Asset not found: {filename} */"
